TheBlog/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='Home'),
    path('about/', views.AboutView.as_view(), name='About'),
    path('post/view/<pk>/', views.PostDetailView.as_view(), name='Post Detail'),
    path('post/new/', views.CreatePostView.as_view(), name='New Post'),
    path('post/<pk>/edit/', views.PostUpdateView.as_view(), name='Post Edit'),
    path('post/<pk>/delete/', views.PostDeleteView.as_view(), name='Post Delete'),
    path('post/<pk>/publish/', views.post_publish, name='Post Publish'),
    path('post/drafts/', views.DraftListView.as_view(), name='Post Drafts List'),
    path('post/<pk>/comment/', views.add_comments_to_post, name='Post Comment'),
    path('comment/<pk>/approve/', views.comment_approve, name='Comment Approve'),
    path('comment/<pk>/delete/', views.comment_remove, name='Comment Delete'),


]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    # first_name = models.CharField(default=author.first_name)
    # last_name = models.CharField(default=au)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:Post Detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name="comments", on_delete=models.CASCADE)
    author = models.CharField(max_length=100, default='Anonymous')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('post_comment', kwargs={'pk': self.post.pk})

blog/forms.py
from django import forms
from blog.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'editable editor-textarea form-control', 'id': 'post-text-input'}),
            # 'author': forms.ChoiceField(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'editable editor-textarea form-control'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from blog.forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.utils import timezone


# Create your views here.


class AboutView(TemplateView):
    template_name = 'blog/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "TheBlog | About"
        return context


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "TheBlog | Home"
        return context


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = 'post'
        return context


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'

    form_class = PostForm
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "New Post"
        return context


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "Edit: " + self.model.title
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:Home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "Delete"
        return context


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = "Drafts"
        return context


@login_required
def add_comments_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:Post Detail', pk=post.pk)
    else:
        form = CommentForm()
        template = 'blog/comment_form.html'
        context = {'Title': post.title,
                   'form': form}
        return render(request, template, context)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:Post Detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:Post Detail', pk=post_pk)


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:Home')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block bd_block %}
<h1 style="text-align: center">About</h1>
    <div class="col-lg-10 about-content">

    </div>


{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ Title }}</title>
    <link rel="stylesheet" href="{% static 'common/css/bootstrap.min.css' %}">
    <script src="{% static 'common/js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'common/css/medium-editor.min.css ' %}">
    <script src="{% static 'common/js/medium-editor.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'common/css/all.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/style-blog.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Cuprum&family=Economica&display=swap" rel="stylesheet">
</head>

<body>
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark nav-color nav-font">
  <a class="navbar-brand brand-size" href="{% url 'blog:Home' %}">TheBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {{ home_active }}">
        <a class="nav-link " href="{% url 'blog:Home' %}">Home

        </a>
      </li>
      <li class="nav-item {{ about_active }}">
        <a class="nav-link" href="{% url 'blog:About' %}">About</a>
      </li>
        {% if user.is_authenticated %}
{#        <li class="nav-item ">#}
{#        <a class="nav-link" href="#">My Posts</a>#}
{#      </li>#}
      <li class="nav-item {{ new_post_active }}">
        <a class="nav-link" href="{% url 'blog:New Post' %}">New Post <i class="fas fa-plus"></i></a>
      </li>
        {% endif %}

{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-555" data-toggle="dropdown"#}
{#          aria-haspopup="true" aria-expanded="false">Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
        {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link waves-effect waves-light" href="{% url 'blog:Post Drafts List' %}"><span class="badge badge-dark">{{ post.all.author }}</span>
          <i style="font-size: 1.5em" class="fas fa-pen-square "></i>
        </a>
      </li>
      <li class="nav-item avatar dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <img src="{% static 'common/images/placeholder.png' %}" class="rounded-circle z-depth-0"
            alt="avatar image" height="35">
        </a>
        <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"
          aria-labelledby="navbarDropdownMenuLink-55">
          <p class="" style="text-align: center">{{ user }}</p>
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}"><span class="fas fa-user"> </span> Login </a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>
<!--/.Navbar -->
<!--/.Navbar -->

{% block bd_block %}

{% endblock %}

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block bd_block %}
<h3>New Comment</h3>
    <div class="container">
<form method="post" class="new-comment">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-primary">Post Comment</button>
<script>var editor = new MediumEditor('.editable')</script>
</form>
    </div>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block bd_block %}
<form method="post" class="delete-confirm">
{% csrf_token %}
    <h5>{{ post.title }}</h5>
<h5>Are you sure you want to delete this post ? <br>(action cannot be reversed)</h5>
<a href="{% url 'blog:Post Detail' pk=post.pk %}"><button type="button" class="btn btn-dark">Cancel</button></a>
<a><button type="submit" class="btn btn-danger">Delete</button></a>
</form>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block bd_block %}
{% if user.is_authenticated and user == post.author%}
<div class="col-lg-4" style="height: 5vh; background-color: #DADAD9;padding: 0">
<ul style="height: 100%;width: 100%; float: left; padding: 0">
    <li class="detail-options "><a href="{% url 'blog:Post Edit' pk=post.pk %}"><div><i class="fas fa-pen"></i> Edit</div></a></li>
<li class="detail-options "><a href="#"><div><i class="fas fa-info"></i> View Info</div></a></li>
<li class="detail-options "><a href="#comments"><div><i class="fas fa-comment"></i> Comment</div></a></li>
<li class="detail-options "><a href="{% url 'blog:Post Delete' pk=post.pk %}"><div><i class="fas fa-trash"></i> Delete</div></a></li>

</ul>
{% else %}
    <a href="{% url 'blog:Home' %}" style="margin-left: 10px; float: left"><i class="fas fa-chevron-left fa-2x"></i></a>
    <a class="detail-options2" href="#comments"><div><i class="fas fa-comment"></i> Comment</div></a>
{% endif %}
</div>
    <div class="col-lg-8 stage" >
    <h2 class="post-title" style="text-align: center;">{{ post.title }}</h2>
    <p class="post-date">
        {% if post.published_date %}
            Date Published: {{ post.published_date }}
            {% else %}
            <a type="button" class="btn btn-primary" href="{% url 'blog:Post Publish' pk=post.pk %}">Publish <i class="fas fa-paper-plane"></i></a>
        {% endif %}
    </p>
    <p class="post-content">{{ post.text|safe|linebreaksbr }}</p>
    </div>

    <div class="container comment-section" id="comments">
        <h4>Comments  <a href="{% url 'blog:Post Comment' pk=post.pk %}"><button class="btn btn-dark">Add Comment</button></a></h4>
    <ul>
        {% for comment in post.comments.all %}
            {% if comment.approved_comment and user != post.author%}
                <li class="post-item" ><a href="{% url 'blog:Post Detail ' pk=post.pk %}">
        <div>
            <h6>{{ comment.author }}</h6>
            <h6><strong></strong> {{ comment.text }}</h6>
            <br><p>Comment Date: {{ comment.created_date }}</p>


        </div>
        </a>
    </li>
                {% elif user == post.author %}
                <li class="post-item" >
        <div >
            <h6>{{ comment.author }}{% if not comment.approved_comment %}(Unapproved){% endif %}</h6>
            <h6><strong></strong> {{ comment.text|safe|linebreaksbr }}</h6>
            <p>Comment Date: {{ comment.created_date }} </p>
        <div>
        {% if not comment.approved_comment %}<a class="btn btn-light" style="position: relative; bottom: 10px; left: 10px; " href="{% url 'blog:Comment Approve' pk=comment.pk%}">Approve <i class="fas fa-check"></i></a>{% endif %}
        <a class="btn btn-light" style="position: relative; bottom: 10px; left: 10px; " href="{% url 'blog:Comment Delete' pk=comment.pk%}">Remove <i class="fas fa-trash"></i></a>
        </div>

        </div>

    </li>
            {% endif %}
        {% empty %}
            <h4>No Comments!</h4>
        {% endfor %}
    </ul>
    </div>


{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block bd_block %}

<div class="col-lg-11 center-stage-info"><h5><strong>Drafts</strong></h5></div>
<div class="col-lg-11 center-stage" style="padding: 0;">
<ul class="post-items" style="padding: 0">


{% for post in post_list%}
    {% if post.author == user %}
    <li class="post-item" ><a href="{% url 'blog:Post Detail' pk=post.pk %}">
        <div>
            <h6>Title: {{ post.title }}</h6>
            <p>{{ post.text|truncatechars:100|safe }}<br><strong>Date Created:</strong> {{ post.created_date }}

        </div>
        </a>
    </li>
    {% endif %}
{% endfor %}
</ul>
</div>



{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block bd_block %}
<h1 style="text-align: center">New post
</h1>
<div class="container">
    <form method="post" class="new-post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn-dark btn form-button" type="submit" name="button">Save</button>
    <script>var editor = new MediumEditor('.editable');</script>
</form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block bd_block %}

<div class="col-lg-11 center-stage-info"><h5><strong>Recent Posts</strong></h5></div>
<div class="col-lg-11 center-stage" style="padding: 0;">
<ul class="post-items" style="padding: 0">


{% for post in post_list%}
    <li class="post-item" ><a href="{% url 'blog:Post Detail' pk=post.pk %}">
        <div>
            <h6>Title: {{ post.title }}</h6>
            <p><strong>author:</strong> {% if post.author.first_name != '' and post.author.last_name != '' %}
                {{ post.author.last_name }} {{ post.author.first_name }} ({{ post.author }})
                {% else %}
                {{ post.author }}
            {% endif %}
                <br><strong>Date Published:</strong> {{ post.published_date }}
                <br><strong>Comments: </strong>{{ post.approve_comments.count}}</p>

        </div>
        </a>
    </li>
{% endfor %}
</ul>
</div>
{% endblock %}